server:
  port: 8081

jwt:
  secret: 4528472B4B6250655368566D597133743677397A24432646294A404D63516654
  timeout: 30000000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: hardeyboi11
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

